apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterrole.name }}
  labels:
    app: {{ .Values.clusterrole.name }}
rules:
- apiGroups:
  - ""
  resources:
    {{- range .Values.clusterrole.resources }}
     - {{ . }} 
    {{- end }}
  verbs:
    {{- range .Values.clusterrole.verbs }}
     - {{ . }}
    {{- end }}
